### ISSUE TITLE
Gapple Cooldown Idea

### ISSUE THREAD

**Issue by YT-Duckyyy** [Henry12960/CustomPVP#16]
Add Item Cooldowns, not just ender pearls.

Like Golden Apples, Bow, Enchanted Golden Apples, potions etcetc

**Comment by Henry12960** [comment]
I will add a setting that you can add cooldown on any item, thanks for the idea

**Comment by PetterLight** [comment]
Good ideia, thanks

**Comment by Henry12960** [comment]
Hello @YT-Duckyyy this resource are added by @fernanACM thanks!
