### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by BoyKage** [Henry12960/CustomPVP#17]
[Server thread/CRITICAL]: Could not load plugin 'CustomPVP': Incompatible network protocol version (plugin requires one of: 527, 534, 544)

**Comment by Henry12960** [comment]
I skipped adding protocol support, excuse me

**Comment by Henry12960** [comment]
[Fixed Version Download ](https://poggit.pmmp.io/ci/Henry12960/CustomPVP/CustomPVP/dev:358)
