### ISSUE TITLE
Future Updates

### ISSUE THREAD

**Issue by Henry12960** [Henry12960/CustomPVP#2]
🌟 • I intend to make this the best pvp plugin for servers and also for Pocketmine-MP, with several unique functions, so I will call contributors and make it a huge project!

💡 • Actually Update ideas
--- 
- [ ] Pvp items sounds - **In Progress**
- [ ] Modify PvP items damage 
- [ ] Add Fast Eat
- [ ]  Add Cps Pop-up Counter
- [ ] Cps Limiter
- [x] Ender Pearl Cooldown
- [x] Death Kick
- [x] Ping Kick
- [x] Add Kill Sound 
- [x] Add Death Effects
- [x] AntiFlight on PvP
- [x] Add Kill Reward 
- [x] Add Kill money
- [x] Add Soup PvP
- [x]  Leeching Mode 
- [x] Kill Particles 
- [x] Add custom kill message
- [x] Add cooldown option 
- [x] Add custom KnockBack
- [x] Add recover health on kill 
---
> I'm out of ideas at the moment, but I'll be back soon...

![images (21)](https://user-images.githubusercontent.com/100979680/185469870-8ad67e88-a0a8-4c19-9904-7c7a60bbbc84.jpeg)

**Comment by PetterLight** [comment]
Perfect

**Comment by LightDev38** [comment]
Could you add Soup PvP function per world?

**Comment by PetterLight** [comment]
> Could you add Soup PvP function per world?

Yes, I a can add

**Comment by Henry12960** [comment]
> Could you add Soup PvP function per world?

Added

**Comment by Henry12960** [comment]
;-;

**Comment by PetterLight** [comment]
Lol, But anyway, the project is going very good

**Comment by Ihsan48** [comment]
GitHub automaticly closed, bruh

**Comment by Henry12960** [comment]
All Features comming soon beta update!
