### ISSUE TITLE
Combat logging

### ISSUE THREAD

**Issue by YasinKalca** [Henry12960/CustomPVP#4]
A way to prevent cheaters from leaving the game right before death.

**Comment by Henry12960** [comment]
Thanks for ideia, I will apply coming soon

**Comment by Henry12960** [comment]
Hello, i need a information about your suggest, you need scorehud support?

**Comment by YasinKalca** [comment]
A scorehud isnt necessary tho exta features are always nice to have

**Comment by Henry12960** [comment]
> A scorehud isnt necessary tho exta features are always nice to have

Thanks
